Nezvinskyi/filmoteka

- .gitignore
- src/hello.js
- src/index.js
> add test branch

- src/styles.css
- src/yarik_test.js
> Change body bg color

- src/sass/common/_base-reset.scss
- src/sass/layouts/_header.scss
- src/sass/utils/_variables.scss
- src/templates/header.hbs
накидала базу по стилям. некоторые штуки надо будет убрать, когда добавятся общие стили.
> Header 2.0

- src/js/modal.js
- src/templates/modal.hbs
> add_modal_template

- src/sass/components/_btn.scss
Класс btn-active-page - навешивается на кнопку страница которой активна.
> Прописал стили для кнопок в header и modal.

- src/sass/layouts/_footer.scss
- src/templates/footer.hbs
Добавляет  и стилизирует свг в футере
> Add svg image to footer

- src/js/header.js
- src/sass/layouts/_header.scss
- src/templates/header.hbs
добавила функи для работы с инпутом/навигацией.
все работает, фон меняется, значение инпута записывается
> Header styles logic

- src/js/get-refs.js
- src/js/header.js
Решила проблему.  заключалась в том что элементы которые рисуются динамически  не были доступны.  Долго объяснять. глянь именно на переменную рефс в хедер джиес , думаю сразу поймешь)
> решает проблему доступности рефов

- src/templates/film-card.hbs
- в шаблоне модалки пока что не те переменные поому и отрисовывается пока не коректно
> Исправил баг с вызовом модалки и отрисовкой фильма

- src/index.js
- src/js/api/storage.js
- src/js/get-refs.js
- src/js/modal.js
- src/js/myLibrary.js
- src/templates/modal.hbs
- fix saving obj-s to localStorage
- -get necessary arrays **to console** for the next step in the project (rendering movies)
> fix saving obj-s to localStorage

- src/js/modal.js
- src/sass/layouts/_modal-card.scss
- src/templates/modal.hbs
adding escape close modal and adding test form of trailer window modal
> adding_escape_close_modal_and_adding_test_form_of_trailer_window_modal

- package.json
- src/js/api/moviesApi.js
- src/js/components/notifications.js
- src/js/gallery.js
- src/js/header.js
- src/sass/layouts/_header.scss
для корректной работы нужно установить пакеты:
npm i notyf
npm i material-icons
> добавляет нотификации

- src/index.html
- src/js/get-refs.js
- src/js/header.js
- src/sass/layouts/_header.scss
- src/templates/header.hbs
пока все в хедере прописано. логика, стили
> добавляет скролл вверх. плавный

- src/js/api/moviesApi.js
поменял year на primary_release_year
> изменил url запрос в getSearchYear

- src/js/api/storage.js
- src/js/components/notifications.js
- src/js/gallery.js
> добавляет нотификацию при удалении/добавлении фильма в очередь

- src/index.html
- src/js/api/storage.js
- src/js/gallery.js
- src/js/header.js
- src/js/myLibrary.js
- src/sass/layouts/_header.scss
- fix rendering myLibrary from localstorage
- fix the modal opening from myLibrary
> fix rendering myLibrary from localstorage

- src/js/api/moviesApi.js
Добавил в URL методов getSearchYear, getSearchGenres, &page=${pageCounter.page}-дает возможность перехода по страницам.
> исправление в moviesApi

- src/sass/layouts/_modal-card.scss
- src/templates/modal.hbs
> additing_primary_modal_styles

- src/js/modal.js
- src/sass/layouts/_modal-card.scss
additing_overflow_hidden_modal+bug"33"
> additing_overflow_hidden_modal+bug"33"

- src/js/modal.js
в модалку при вызове регистрации вставляеться другая разметка и потому не находился элемент на который вешался слушатель и это давало ошибку мешавшую работе окна регистрации
> пофиксил ошибку мешавшую работе модалки регистрации

- src/js/modal.js
> все таки убирает баг со скроллом при закрытии

- src/js/api/storage.js
Вызов   checkLocalStorage(); при очистки LocalStorage  (ошибка если нет пустого обьекта)
> checkLocalStorage

- src/html/team-modal.html
- src/js/team-modal.js
- src/sass/layouts/_team-modal.scss
> additibg team modal

- src/js/firebase.js
1. был пункт 1, переписал его вывод в консоль на 1 а) (обработчик watched), 
2. 1 б) ((обработчик queue))
3. 1 в), 1 г) - сохраняют ид-ки в localStorage (с ключами )
> save idx to localstorage

- src/html/auth-in-modal.html
- src/js/auth.js
Теперь клик по кнопкам вызывает соответствующие методы класа (регистрацию и вход) а не просто событие submit
> Изменил логику работы кнопок sign in и sign up.

- src/js/api/storage.js
- src/sass/components/_btn.scss
- src/sass/layouts/_modal-card.scss
Изменение цвета кнопок при ховере в модалке
> change-color-btn (hover)

- src/js/api/storage.js
Пофиксил закрашивание кнопок модалки (на старом варианте ) LocalStorage
> storage.js classList on wachedBtn

- src/index.html
- src/templates/header.hbs
Reverts Nezvinskyi/filmoteka#164
> Revert "Test Google auth"

- src/js/api/auth.js
- src/js/gallery.js
- src/js/header.js
Отловил и вывел в нотификашки ошибки входа и регистрации
> Auth andreys db

- src/js/api/db.js
- src/js/api/storage.js
- src/js/modal.js
- src/sass/components/_btn.scss
1.Кнопки модалки получают айди из fb  и на его основе отрисовываються.
2.Рефактор файла storage.js
3. Корекция стилей кнопки.
4.Удаление лишних консолей.
> refactor-btn-style

- src/js/api/auth.js
- src/js/gallery.js
- src/js/get-refs.js
- src/js/myLibrary.js
- src/sass/components/_loader.scss
- src/templates/header.hbs
74 строчка в auth.js решает проблему закрытия модалки после успешной регистрации
> Auth button logic

- src/js/api/storage.js
Баг удаления последнего фильма исправлен
> fixed delete of last film from storage
